### ISSUE TITLE
What is the actual hex code for the new color for comments and also what is the text font that you're using in the preview ?

### ISSUE THREAD

**Issue by astrolemonade** [dszopa/better-one-dark-comments-syntax#1]

**Comment by dszopa** [comment]
The equivalent hex color would be `#acbca9`, for the editor it's [defined as `hsl` here.](https://github.com/dszopa/better-one-dark-comments-syntax/blob/master/styles/colors.less#L34)

I'm not quite sure what font I was using in the screenshot at the time, my best guess is that it's `menlo`.

**Comment by astrolemonade** [comment]
Thank you
